# Generated by Django 4.2.17 on 2025-01-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUsForm',
            new_name='ContactUsModel',
        ),
    ]
