# Generated by Django 5.0.1 on 2024-02-05 05:26

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/image')),
                ('regular_price', models.IntegerField()),
                ('sale_price', models.IntegerField(blank=True, null=True)),
                ('sku', models.IntegerField(unique=True)),
                ('dimenstions', models.IntegerField(blank=True, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('category', models.ManyToManyField(related_name='category', to='product.category')),
                ('tag', models.ManyToManyField(related_name='tag', to='product.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/gallery')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery', to='product.product')),
            ],
        ),
    ]