# Generated by Django 5.0.1 on 2024-02-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimenstions',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
