# Generated by Django 5.0.1 on 2024-02-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
