# Generated by Django 5.0.1 on 2024-02-05 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productvariation_product_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='attribute_value',
        ),
        migrations.AddField(
            model_name='gallery',
            name='productvariation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variation_gallery', to='product.productvariation'),
        ),
    ]
