# Generated by Django 5.0.1 on 2024-02-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0005_remove_attribute_product'),
        ('product', '0005_remove_productvariation_attribute_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(limit_choices_to={'variations__isnull': False}, related_name='products', through='product.ProductVariation', to='attribute.attribute'),
        ),
    ]
