# Generated by Django 5.0.1 on 2024-02-05 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0005_remove_attribute_product'),
        ('product', '0006_alter_product_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='attribute',
            field=models.ForeignKey(limit_choices_to={'variations__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute'),
        ),
    ]
