# Generated by Django 5.0.1 on 2024-02-05 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0005_remove_attribute_product'),
        ('product', '0007_alter_productvariation_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(related_name='products', through='product.ProductVariation', to='attribute.attribute'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute'),
        ),
    ]
