# Generated by Django 5.0.1 on 2024-02-05 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0005_remove_attribute_product'),
        ('product', '0009_remove_productvariation_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.variations'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute'),
        ),
    ]
