# Generated by Django 5.0.1 on 2024-02-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productvariation_variation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='productvariation',
        ),
    ]
