# Generated by Django 5.0.1 on 2024-02-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productattribute_product_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_attribute', to='product.productattribute'),
        ),
    ]
