# Generated by Django 5.0.1 on 2024-02-05 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_gallery_gallery_attribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='gallery_attribute',
        ),
        migrations.CreateModel(
            name='GalleryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop/gallery/attribute')),
                ('gallery_attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_attribute', to='product.productattribute')),
            ],
        ),
    ]
