# Generated by Django 5.0.1 on 2024-02-05 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_gallery_gallery_attribute_galleryattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.DeleteModel(
            name='GalleryAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
