# Generated by Django 5.0.1 on 2024-02-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0005_remove_attribute_product'),
        ('product', '0017_remove_productattribute_attribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute',
            field=models.ManyToManyField(related_name='attribute', to='attribute.attribute'),
        ),
    ]
