# Generated by Django 5.0.1 on 2024-02-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='regular_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='variant',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
