# Generated by Django 5.0.1 on 2024-02-05 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0005_remove_attribute_product'),
        ('product', '0020_rename_regular_price_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.attribute'),
        ),
        migrations.AddField(
            model_name='variant',
            name='variations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.variations'),
        ),
    ]
