# Generated by Django 5.0.1 on 2024-02-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_variant_attribute_alter_variant_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='variations',
        ),
    ]
