# Generated by Django 5.0.1 on 2024-02-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_variantgallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariantGallery',
        ),
    ]
