# Generated by Django 5.0.1 on 2024-02-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_galleryvariations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryvariations',
            name='title',
        ),
    ]
