# Generated by Django 5.0.1 on 2024-02-06 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_remove_galleryvariations_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='image_id',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='stock_quantity',
        ),
    ]
