# Generated by Django 5.0.1 on 2024-02-06 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0005_remove_attribute_product'),
        ('product', '0031_remove_variant_image_id_remove_variant_sale_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='regular_price',
        ),
        migrations.AddField(
            model_name='variant',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.attribute'),
        ),
        migrations.AddField(
            model_name='variant',
            name='image_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
