# Generated by Django 5.0.1 on 2024-02-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_remove_variant_regular_price_variant_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='image_id',
        ),
    ]
