# Generated by Django 4.2.17 on 2024-12-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(default=0),
        ),
    ]
