# Generated by Django 4.2.17 on 2025-01-29 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_alter_productcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistProducs',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
