# Generated by Django 4.2.17 on 2025-01-29 09:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0010_alter_wishlistproducs_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishlistProducs',
            new_name='WishlistProducts',
        ),
    ]
