# Generated by Django 4.2.17 on 2025-02-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_wishlistproducs_wishlistproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
