# Generated by Django 4.2.17 on 2025-01-20 08:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='coupon_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
