# Generated by Django 4.2.17 on 2025-01-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'در حال انتظار'), (2, 'در حال پردازش'), (3, 'در حال ارسال'), (4, 'ارسال شده'), (5, 'لغو شده'), (6, 'عودت داده شده')], default=1),
        ),
    ]
