# Generated by Django 4.2.17 on 2025-01-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_coupon_at_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon_at_order',
            field=models.IntegerField(default=0),
        ),
    ]
