# Generated by Django 4.2.17 on 2025-01-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_coupon_at_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['-created_at']},
        ),
    ]
