# Generated by Django 5.0.1 on 2024-02-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
