# Generated by Django 5.0.1 on 2024-02-05 06:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_alter_variations_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variations',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variations'),
        ),
    ]
