# Generated by Django 5.0.1 on 2024-02-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_color_remove_variations_attribute_delete_attribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeltSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
