# Generated by Django 5.0.1 on 2024-02-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0004_attribute_product_alter_attribute_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='product',
        ),
    ]
